const db = require('./database/firebase');

const products = [
  { name: 'Samsung Galaxy S24 Ultra', slug: 'samsung-galaxy-s24-ultra', price: 350000, sale_price: 330000, stock: 15, category_name: 'Smartphones', category_id: 'smartphones', description: 'The ultimate Galaxy smartphone with AI features, a titanium frame, and an amazing camera system.', brand: 'Samsung', images: ['https://placehold.co/600x600?text=Galaxy+S24+Ultra'], is_active: 1, created_at: Date.now() },
  { name: 'Apple iPhone 15 Pro Max', slug: 'apple-iphone-15-pro-max', price: 420000, sale_price: 400000, stock: 10, category_name: 'Smartphones', category_id: 'smartphones', description: 'Titanium design, A17 Pro chip, and the most advanced Pro camera system ever.', brand: 'Apple', images: ['https://placehold.co/600x600?text=iPhone+15+Pro+Max'], is_active: 1, created_at: Date.now() },
  { name: 'Sony WH-1000XM5 Wireless Headphones', slug: 'sony-wh-1000xm5', price: 110000, sale_price: 95000, stock: 25, category_name: 'Audio', category_id: 'audio', description: 'Industry-leading noise cancellation, magnificent sound, and unmatched call quality.', brand: 'Sony', images: ['https://placehold.co/600x600?text=Sony+WH-1000XM5'], is_active: 1, created_at: Date.now() },
  { name: 'Apple MacBook Pro M3', slug: 'apple-macbook-pro-m3', price: 650000, sale_price: 620000, stock: 8, category_name: 'Laptops', category_id: 'laptops', description: 'Supercharged by M3, featuring a brilliant Liquid Retina XDR display and long battery life.', brand: 'Apple', images: ['https://placehold.co/600x600?text=MacBook+Pro+M3'], is_active: 1, created_at: Date.now() },
  { name: 'Samsung 55" Neo QLED 4K TV', slug: 'samsung-55-neo-qled-4k-tv', price: 380000, sale_price: 350000, stock: 5, category_name: 'Televisions', category_id: 'televisions', description: 'Experience breathtaking 4K clarity, rich colors, and slim design.', brand: 'Samsung', images: ['https://placehold.co/600x600?text=Samsung+Neo+QLED'], is_active: 1, created_at: Date.now() },
  { name: 'Dell XPS 15', slug: 'dell-xps-15', price: 550000, sale_price: 520000, stock: 12, category_name: 'Laptops', category_id: 'laptops', description: 'Stunning 4K OLED display and powerful Intel Core processors in a thin, light design.', brand: 'Dell', images: ['https://placehold.co/600x600?text=Dell+XPS+15'], is_active: 1, created_at: Date.now() },
  { name: 'Nintendo Switch OLED', slug: 'nintendo-switch-oled', price: 120000, sale_price: 110000, stock: 30, category_name: 'Gaming', category_id: 'gaming', description: 'Play at home or on the go with a vibrant 7-inch OLED screen.', brand: 'Nintendo', images: ['https://placehold.co/600x600?text=Nintendo+Switch+OLED'], is_active: 1, created_at: Date.now() },
  { name: 'PlayStation 5 Console', slug: 'playstation-5', price: 210000, sale_price: 195000, stock: 20, category_name: 'Gaming', category_id: 'gaming', description: 'Lightning fast loading, ultra-high speed SSD, and breathtaking immersion.', brand: 'Sony', images: ['https://placehold.co/600x600?text=PlayStation+5'], is_active: 1, created_at: Date.now() },
  { name: 'Xbox Series X', slug: 'xbox-series-x', price: 195000, sale_price: 185000, stock: 15, category_name: 'Gaming', category_id: 'gaming', description: 'The fastest, most powerful Xbox ever. True 4K gaming and 120 FPS.', brand: 'Microsoft', images: ['https://placehold.co/600x600?text=Xbox+Series+X'], is_active: 1, created_at: Date.now() },
  { name: 'Apple Watch Series 9', slug: 'apple-watch-series-9', price: 140000, sale_price: 130000, stock: 25, category_name: 'Wearables', category_id: 'wearables', description: 'Smarter, brighter, and mightier. Featuring Double Tap gesture.', brand: 'Apple', images: ['https://placehold.co/600x600?text=Apple+Watch+Series+9'], is_active: 1, created_at: Date.now() },
  { name: 'Samsung Galaxy Watch 6', slug: 'samsung-galaxy-watch-6', price: 95000, sale_price: 85000, stock: 22, category_name: 'Wearables', category_id: 'wearables', description: 'Advanced sleep coaching, personalized heart rate zones, and a larger screen.', brand: 'Samsung', images: ['https://placehold.co/600x600?text=Galaxy+Watch+6'], is_active: 1, created_at: Date.now() },
  { name: 'Bose QuietComfort Earbuds II', slug: 'bose-qc-earbuds-2', price: 105000, sale_price: 95000, stock: 18, category_name: 'Audio', category_id: 'audio', description: 'CustomTune sound calibration and the world\'s best noise cancellation.', brand: 'Bose', images: ['https://placehold.co/600x600?text=Bose+QC+Earbuds'], is_active: 1, created_at: Date.now() },
  { name: 'LG C3 OLED 65" TV', slug: 'lg-c3-oled-65', price: 650000, sale_price: 600000, stock: 4, category_name: 'Televisions', category_id: 'televisions', description: 'OLED evo technology for stunning picture quality and brightness.', brand: 'LG', images: ['https://placehold.co/600x600?text=LG+C3+OLED'], is_active: 1, created_at: Date.now() },
  { name: 'Google Pixel 8 Pro', slug: 'google-pixel-8-pro', price: 320000, sale_price: 295000, stock: 12, category_name: 'Smartphones', category_id: 'smartphones', description: 'The most powerful Pixel yet with Google AI and the best Pixel camera.', brand: 'Google', images: ['https://placehold.co/600x600?text=Pixel+8+Pro'], is_active: 1, created_at: Date.now() },
  { name: 'ASUS ROG Strix G15', slug: 'asus-rog-strix-g15', price: 420000, sale_price: 390000, stock: 7, category_name: 'Laptops', category_id: 'laptops', description: 'High-performance gaming laptop with NVIDIA GeForce RTX graphics.', brand: 'ASUS', images: ['https://placehold.co/600x600?text=ASUS+ROG+Strix'], is_active: 1, created_at: Date.now() },
  { name: 'GoPro HERO12 Black', slug: 'gopro-hero12-black', price: 150000, sale_price: 135000, stock: 20, category_name: 'Cameras', category_id: 'cameras', description: 'Incredible 5.3K video, HyperSmooth 6.0 stabilization, and longer battery life.', brand: 'GoPro', images: ['https://placehold.co/600x600?text=GoPro+HERO12'], is_active: 1, created_at: Date.now() },
  { name: 'Canon EOS R6 Mark II', slug: 'canon-eos-r6-mk2', price: 850000, sale_price: 820000, stock: 3, category_name: 'Cameras', category_id: 'cameras', description: 'A versatile hybrid mirrorless camera with blazing fast autofocus.', brand: 'Canon', images: ['https://placehold.co/600x600?text=Canon+EOS+R6'], is_active: 1, created_at: Date.now() },
  { name: 'DJI Mini 4 Pro', slug: 'dji-mini-4-pro', price: 380000, sale_price: 360000, stock: 6, category_name: 'Drones', category_id: 'drones', description: 'Mini camera drone with omnidirectional obstacle sensing.', brand: 'DJI', images: ['https://placehold.co/600x600?text=DJI+Mini+4+Pro'], is_active: 1, created_at: Date.now() },
  { name: 'JBL Charge 5', slug: 'jbl-charge-5', price: 45000, sale_price: 38000, stock: 40, category_name: 'Audio', category_id: 'audio', description: 'Portable Bluetooth speaker with IP67 waterproof rating and powerbank.', brand: 'JBL', images: ['https://placehold.co/600x600?text=JBL+Charge+5'], is_active: 1, created_at: Date.now() },
  { name: 'Logitech MX Master 3S', slug: 'logitech-mx-master-3s', price: 35000, sale_price: 32000, stock: 35, category_name: 'Accessories', category_id: 'accessories', description: 'Advanced wireless mouse with 8K DPI tracking and quiet clicks.', brand: 'Logitech', images: ['https://placehold.co/600x600?text=MX+Master+3S'], is_active: 1, created_at: Date.now() },
  { name: 'Keychron K2 Wireless Mechanical Keyboard', slug: 'keychron-k2', price: 42000, sale_price: 39000, stock: 15, category_name: 'Accessories', category_id: 'accessories', description: '75% layout wireless mechanical keyboard for Mac and Windows.', brand: 'Keychron', images: ['https://placehold.co/600x600?text=Keychron+K2'], is_active: 1, created_at: Date.now() },
  { name: 'Apple iPad Air (5th Gen)', slug: 'apple-ipad-air-5', price: 210000, sale_price: 190000, stock: 12, category_name: 'Tablets', category_id: 'tablets', description: 'Supercharged by the M1 chip with a 10.9-inch Liquid Retina display.', brand: 'Apple', images: ['https://placehold.co/600x600?text=iPad+Air+5'], is_active: 1, created_at: Date.now() },
  { name: 'Samsung Galaxy Tab S9', slug: 'samsung-galaxy-tab-s9', price: 280000, sale_price: 260000, stock: 10, category_name: 'Tablets', category_id: 'tablets', description: 'Premium Android tablet with an immersive Dynamic AMOLED 2X display.', brand: 'Samsung', images: ['https://placehold.co/600x600?text=Galaxy+Tab+S9'], is_active: 1, created_at: Date.now() },
  { name: 'Amazon Kindle Paperwhite', slug: 'amazon-kindle-paperwhite', price: 55000, sale_price: 49000, stock: 25, category_name: 'Tablets', category_id: 'tablets', description: '6.8" display, adjustable warm light, and up to 10 weeks of battery life.', brand: 'Amazon', images: ['https://placehold.co/600x600?text=Kindle+Paperwhite'], is_active: 1, created_at: Date.now() },
  { name: 'Samsung 1TB Portable SSD T7', slug: 'samsung-1tb-ssd-t7', price: 45000, sale_price: 40000, stock: 30, category_name: 'Accessories', category_id: 'accessories', description: 'Lightning-fast external storage in a compact, durable design.', brand: 'Samsung', images: ['https://placehold.co/600x600?text=Samsung+SSD+T7'], is_active: 1, created_at: Date.now() },
  { name: 'Anker PowerCore 20000mAh', slug: 'anker-powercore-20000', price: 18000, sale_price: 15000, stock: 50, category_name: 'Accessories', category_id: 'accessories', description: 'High-capacity portable charger for multiple smartphone charges.', brand: 'Anker', images: ['https://placehold.co/600x600?text=Anker+Powerbank'], is_active: 1, created_at: Date.now() },
  { name: 'Razer DeathAdder V3 Pro', slug: 'razer-deathadder-v3-pro', price: 55000, sale_price: 48000, stock: 15, category_name: 'Accessories', category_id: 'accessories', description: 'Ultra-lightweight wireless ergonomic esports mouse.', brand: 'Razer', images: ['https://placehold.co/600x600?text=Razer+DeathAdder'], is_active: 1, created_at: Date.now() },
  { name: 'HyperX Cloud II Wireless', slug: 'hyperx-cloud-2-wireless', price: 52000, sale_price: 45000, stock: 20, category_name: 'Audio', category_id: 'audio', description: 'Legendary comfort and sound in a wireless gaming headset.', brand: 'HyperX', images: ['https://placehold.co/600x600?text=HyperX+Cloud+II'], is_active: 1, created_at: Date.now() },
  { name: 'Secretlab TITAN Evo 2022', slug: 'secretlab-titan-evo', price: 180000, sale_price: 170000, stock: 5, category_name: 'Furniture', category_id: 'furniture', description: 'Premium gaming chair designed for all-day comfort and support.', brand: 'Secretlab', images: ['https://placehold.co/600x600?text=Secretlab+TITAN'], is_active: 1, created_at: Date.now() },
  { name: 'Dyson V15 Detect Vacuum', slug: 'dyson-v15-detect', price: 250000, sale_price: 230000, stock: 8, category_name: 'Home Appliances', category_id: 'home-appliances', description: 'Powerful, intelligent cordless vacuum with laser illumination.', brand: 'Dyson', images: ['https://placehold.co/600x600?text=Dyson+V15'], is_active: 1, created_at: Date.now() },
];

async function seed() {
  console.log('Starting seed...');
  for (const product of products) {
    const newRef = db.ref('products').push();
    await newRef.set(product);
    console.log(`Added: ${product.name}`);
  }
  console.log('Seed completed.');
  process.exit(0);
}

seed();
